
name: Deploy Venuevista

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - name: backup .env
        run: |
          if [ -f .env ]; then mv .env /temp/env_backup; fi
          
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: restore .env
        run: |
          if [ -f /temp/env_backup ]; then mv /temp/env_backup .env; fi

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm

      - name: Install Dependencies
        run: npm ci

      - name: Restart application
        run: |
          pm2 describe mainApp >/dev/null \
           && pm2 restart mainApp --update-env \
           || pm2 start npm --name mainApp -- start
          
          pm2 save

